/**
 * Push the repo's routing profiles to the live engine over HTTP.
 *
 * BRouter's RouteServer accepts `POST /brouter/profile/<custom_id>` and
 * stores the body as `<custom dir>/<id>.brf` (verified locally: upload →
 * `{"profileid":"custom_<id>"}`, re-upload to the same id updates it,
 * `profile=custom_<id>` routes). With a stable id per profile the app can
 * ship profile changes without re-provisioning the server. Requires the
 * server's custom-profile directory to be configured relative to its
 * profiles directory (cloud-init v3 does this; v2 does not).
 *
 * Profiles come from src/data/engine-profiles.json, generated by
 * scripts/routing/build-cloud-init.mjs from scripts/routing/profiles/*.brf.
 */

import profiles from "@/data/engine-profiles.json";

/**
 * The engine assigns the id on first upload (`POST /brouter/profile` →
 * `{"profileid":"custom_<n>"}`); updating in place requires that id
 * (`POST /brouter/profile/custom_<n>`, which refuses unknown ids). So the
 * app keeps the ids in env: BROUTER_ROAD_PROFILE / BROUTER_ROAD_RELAXED_PROFILE.
 */
export const PROFILE_ENV: Record<string, string> = {
  "loops-road": "BROUTER_ROAD_PROFILE",
  "loops-road-relaxed": "BROUTER_ROAD_RELAXED_PROFILE",
};

export interface ProfileSyncResult {
  name: string;
  /** The custom id now holding this profile (new or updated). */
  id: string | null;
  created: boolean;
  verified: boolean;
  detail: string;
}

/** Short Dublin test leg — any tile set we run includes Ireland. */
const VERIFY_LONLATS = "-6.17,53.3625|-6.25,53.40";

export async function syncEngineProfiles(
  baseUrl: string,
  existingIds: Record<string, string | undefined> = {}
): Promise<ProfileSyncResult[]> {
  const base = baseUrl.replace(/\/$/, "");
  const out: ProfileSyncResult[] = [];
  for (const [name, text] of Object.entries(profiles as Record<string, string>)) {
    if (!PROFILE_ENV[name]) continue;
    const known = existingIds[name];
    const useExisting = !!known && /^custom_\d+$/.test(known);
    const r: ProfileSyncResult = { name, id: useExisting ? known! : null, created: false, verified: false, detail: "" };
    try {
      const up = await fetch(useExisting ? `${base}/profile/${known}` : `${base}/profile`, {
        method: "POST",
        headers: { "Content-Type": "text/plain" },
        body: text,
        signal: AbortSignal.timeout(10_000),
      });
      const body = await up.text();
      const m = body.match(/"profileid"\s*:\s*"(custom_\d+)"/);
      if (!up.ok || !m) {
        r.detail = `upload http ${up.status}: ${body.slice(0, 120).replace(/\s+/g, " ")}`;
        out.push(r);
        continue;
      }
      r.id = m[1];
      r.created = !useExisting;
      const test = await fetch(
        `${base}?lonlats=${VERIFY_LONLATS}&profile=${r.id}&alternativeidx=0&format=geojson`,
        { signal: AbortSignal.timeout(20_000) }
      );
      const t = await test.text();
      r.verified = test.ok && t.includes("FeatureCollection");
      r.detail = r.verified
        ? `${useExisting ? "updated" : "created"} ${r.id} and routed a test leg`
        : `routing http ${test.status}: ${t.slice(0, 120).replace(/\s+/g, " ")}`;
    } catch (e) {
      r.detail = `error: ${e instanceof Error ? e.message : String(e)}`;
    }
    out.push(r);
  }
  return out;
}
